package Interfaces;

public enum ChessPieceEnums {

    WHITE_PAWN,WHITE_ROOK,WHITE_BISHOP,WHITE_KNIGHT,WHITE_KING,WHITE_QUEEN,
    BLACK_PAWN,BLACK_ROOK,BLACK_BISHOP,BLACK_KNIGHT,BLACK_KING,BLACK_QUEEN,
}
